# Generated by Django 4.1.7 on 2024-10-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('kname', models.CharField(max_length=200)),
                ('mode', models.CharField(max_length=200)),
                ('pname', models.CharField(max_length=200)),
            ],
        ),
    ]
